# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/mfeldahby/Desktop/project_2 _draft_1/project_2 _draft_1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/mfeldahby/Desktop/project_2 _draft_1/project_2 _draft_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo {c:/Users/mfeldahby/Desktop/project_2 _draft_1/project_2 _draft_1.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/mfeldahby/Desktop/project_2 _draft_1/project_2 _draft_1.srcs/sources_1/new/BCD.v}
  {C:/Users/mfeldahby/Desktop/project_2 _draft_1/project_2 _draft_1.srcs/sources_1/new/synchron.v}
  {C:/Users/mfeldahby/Desktop/project_2 _draft_1/project_2 _draft_1.srcs/sources_1/new/subtraction.v}
  {C:/Users/mfeldahby/Desktop/project_2 _draft_1/project_2 _draft_1.srcs/sources_1/new/edgedec.v}
  {C:/Users/mfeldahby/Desktop/project_2 _draft_1/project_2 _draft_1.srcs/sources_1/new/division.v}
  {C:/Users/mfeldahby/Desktop/project_2 _draft_1/project_2 _draft_1.srcs/sources_1/new/debouncer.v}
  {C:/Users/mfeldahby/Desktop/project_2 _draft_1/project_2 _draft_1.srcs/sources_1/new/count.v}
  {C:/Users/mfeldahby/Desktop/project_2 _draft_1/project_2 _draft_1.srcs/sources_1/new/clockDivider.v}
  {C:/Users/mfeldahby/Desktop/project_2 _draft_1/project_2 _draft_1.srcs/sources_1/new/addition.v}
  {C:/Users/mfeldahby/Desktop/project_2 _draft_1/project_2 _draft_1.srcs/sources_1/new/multiplication.v}
  {C:/Users/mfeldahby/Desktop/project_2 _draft_1/project_2 _draft_1.srcs/sources_1/new/calc.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/mfeldahby/Desktop/project_2 _draft_1/project_2 _draft_1.srcs/constrs_1/new/cons.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/mfeldahby/Desktop/project_2 _draft_1/project_2 _draft_1.srcs/constrs_1/new/cons.xdc}}]


synth_design -top calc -part xc7a35tcpg236-1


write_checkpoint -force -noxdef calc.dcp

catch { report_utilization -file calc_utilization_synth.rpt -pb calc_utilization_synth.pb }
